version: "3.8"

services:
  backend_service:
    build: .
    env_file: .env
    depends_on:
      - postgres_service
    ports:
      - '8000:8000'

  postgres_service:
    image: postgres:alpine
    ports:
      - '5432:5432'
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_service:
      image: redis/redis-stack:latest
      ports:
        - "6379:6379"
      volumes:
        - /path/to/local/d–∞ta:/root/redis
        - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  postgres_data: